// <auto-generated />
namespace EPayments.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class delUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201903040901374_del Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
